version: "3"
services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./:/app
        command: >
            sh -c "
            alembic upgrade head
            && python -m uvicorn main:app"
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: mariadb
        ports:
            - "3307:3306"
        env_file:
            - .env

        environment:
            - MARIADB_DATABASE=${MARIADB_DATABASE}
            - MARIADB_USER=${MARIADB_USER}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
            - MYSQL_HOST=db
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
        driver: local
