"""'migration_nodes_workflow3'

Revision ID: 0d5c06e9e878
Revises: ee67cb584b44
Create Date: 2024-05-28 11:25:01.414114

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d5c06e9e878"
down_revision: Union[str, None] = "ee67cb584b44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add auto-increment behavior to node.id column
    # op.alter_column("node", "id", autoincrement=True)
    # op.execute("ALTER TABLE node ADD COLUMN id SERIAL PRIMARY KEY")
    op.add_column(
        "node",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
    )

    # Add auto-increment behavior to condition_edge.id column
    # op.alter_column("condition_edge", "id", autoincrement=True)


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("ALTER TABLE node DROP COLUMN id")
    op.drop_column("node", "id")
    # ### end Alembic commands ###
