"""'migration_nodes_workflow'

Revision ID: 35a72f045498
Revises: e43cccb1f5b1
Create Date: 2024-05-28 10:46:12.113051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a72f045498'
down_revision: Union[str, None] = 'e43cccb1f5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'condition_edge', 'condition', ['condition_node_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'condition_edge', type_='foreignkey')
    # ### end Alembic commands ###
