"""'migration_nodes_workflow4'

Revision ID: 5b16377f2456
Revises: 0d5c06e9e878
Create Date: 2024-05-28 11:40:43.170312

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b16377f2456"
down_revision: Union[str, None] = "0d5c06e9e878"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("ALTER TABLE node ADD COLUMN id SERIAL PRIMARY KEY")
    op.alter_column("node", "id", autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.execute("ALTER TABLE node DROP COLUMN id")
    # ### end Alembic commands ###
