"""'migration_nodes_workflow4'

Revision ID: 61da67f93a82
Revises: 5b16377f2456
Create Date: 2024-05-28 12:03:32.630427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61da67f93a82'
down_revision: Union[str, None] = '5b16377f2456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
