services:
    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ..:/app/
        command: ["sh", "-c", "docker/wait_for_it.sh db:3306 -- docker/start.sh"]

        env_file:
            - ../.env
        depends_on:
            - db

    db:
        image: mariadb
        ports:
            - "3307:3306"
        env_file:
            - ../.env

        environment:
            - MARIADB_DATABASE=${MARIADB_DATABASE}
            - MARIADB_USER=${MARIADB_USER}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
            - MYSQL_HOST=db

        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
        driver: local
